name: Java CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version

      # Step 2: Set up JDK 11 with the latest version of setup-java
      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Updated to version v3 to support Node.js 20
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4  # Updated to version v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Run Gradle build
      - name: Build with Gradle
        run: ./gradlew assemble

      # Step 5: Run Gradle tests
      - name: Run tests with Gradle
        run: ./gradlew test

      # Step 6: Archive the JAR files
      - name: Archive JAR files
        uses: actions/upload-artifact@v3  # Latest version for artifact uploading
        with:
          name: build-artifacts
          path: build/libs/*.jar
